# Generated by Django 5.0.4 on 2024-04-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_transaction_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
    ]
